### ISSUE TITLE
s3fs is not optional

### ISSUE THREAD

**Issue by stevemandl** [dazza-codes/pytest-aiomoto#26]
Error if I run `pytest --fixtures` :
```
...
  File "/home/steve/.local/share/virtualenvs/job-wheYVwOM/lib/python3.9/site-packages/pytest_aiomoto/aws_credentials.py", line 28, in <module>
    from s3fs import S3FileSystem
ImportError: Error importing plugin "pytest_aiomoto.aws_credentials": No module named 's3fs'
```
If I add s3fs to the pipfile in my project, it works but I think s3fs should not be optional in your package.

**Comment by dazza-codes** [comment]
Thanks for reporting this.  The package currently has s3fs as an optional dependency, but some of the fixtures might require it, so they are not guarded by a try/except for the import error when s3fs is not available.  Since there are tricky details with s3fs caching credentials, it might be a better idea to make s3fs a required dependency.  Now that s3fs offers the option to include compatible optional dependencies for boto3 and awscli, I'm going to explore a new release that is in sync with s3fs and allow s3fs/aiobotocore to manage the rest of the AWS SDK dependencies.

**Comment by dazza-codes** [comment]
This should be fixed in https://github.com/dazza-codes/pytest-aiomoto/pull/27 and a new release.

**Comment by dazza-codes** [comment]
Try https://pypi.org/project/pytest-aiomoto/ at 0.7.1
